name: Cloud Banking CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-java:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Build Account Service
      run: |
        cd java-services/account-service
        mvn clean package

    - name: Build Transaction Service
      run: |
        cd java-services/transaction-service
        mvn clean package

  docker-build:

    needs: build-java
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Build Docker Images
      run: docker compose build

  integration-test:

    needs: docker-build
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Start System
      run: docker compose up -d

    - name: Wait for containers
      run: sleep 30

    - name: Show Running Containers
      run: docker ps
