name: Docker Compose CI

on:
  push:
    branches: ["main"]

jobs:
  docker:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build Docker containers
      run: docker compose build

    - name: Start services
      run: docker compose up -d

    - name: Show running containers
      run: docker ps
